apiVersion: v1
kind: Service
metadata:
  name: {{ template "sentry.fullname" . }}-taskbroker
  annotations:
    {{- range $key, $value := .Values.taskbroker.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  selector:
    app: {{ template "sentry.fullname" . }}
    role: taskbroker
